### ISSUE TITLE
Copy needed

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/hourglass#216]
- [x] [OLH Award](https://olhbeta.janeway.systems/site/olh-award/) https://github.com/BirkbeckCTP/hourglass/blob/af0c2b87f06c271fe80639eb80fcf4960f72dbb2/templates/custom/olh-award.html#L30
- [x] [OLH Model infographic](https://olhbeta.janeway.systems/site/olh-model/#how-it-works-infographic) (3 places) https://github.com/BirkbeckCTP/hourglass/blob/af0c2b87f06c271fe80639eb80fcf4960f72dbb2/templates/custom/how-it-works-infographic.html#L49
- [x] [Zombie poster](https://olhbeta.janeway.systems/site/olh-poster-series/#zombie-poster) https://github.com/BirkbeckCTP/hourglass/blob/af0c2b87f06c271fe80639eb80fcf4960f72dbb2/templates/custom/olh-poster-series.html#L218
- [x] [Our supporters](https://olhbeta.janeway.systems/plugins/supporters/) https://github.com/BirkbeckCTP/hourglass/blob/af0c2b87f06c271fe80639eb80fcf4960f72dbb2/templates/custom/supporters.html#L33

**Comment by Astronaut-resting** [comment]
@joemull 

Pig latin copy: 

**Supporters** 

_request to delete find out more button as it takes user in a circle._ 


Bold: The OLH is supported by an international network of library partners. 

Unbold: Our supporters share our mission of returning academic journals into community governance and building a sustainable transition towards not-for-profit open access publishing. OLH library members range from national research funding councils and world-leading university libraries, to museum libraries, technology institutes, and liberal arts colleges.


Zombie poster:

The seventh poster in our series was designed by Nicky Borowiec to celebrate Open Access Week 2023 (and its proximity to Halloween). The Zombie Poster commemorates the term ‘zombie journal’, first used by linguists in 2015 following the mass resignation of editors at the Elsevier journal _Lingua_. Protesting Elsevier’s claim to ‘own’ their journal, the international linguistics community boycotted _Lingua_ and launched the community-owned open access journal _Glossa_ in its place (published by the OLH). What was left behind was dubbed ‘Zombie Lingua’. With the commission of this original artwork, we celebrate the spirit that made this political action possible and preserve it for the public record.


Award:


Bold: The Open Library of Humanities Award seeks to recognise and honour individuals who have made outstanding contributions to the advancement of open scholarship. 

By acknowledging the outstanding efforts of individuals, the Open Library of Humanities Award aims to recognise the value of individual endeavours in open access and encourage others to actively engage in the promotion of open scholarship and its principles.




Martin Paul Eve, 2023

The inaugural Open Library of Humanities Award 2023 was awarded to Prof. Martin Paul Eve. Martin's outstanding record of scholarly research is matched by a deep commitment to principles of open access and the protection of community-led open source publishing technologies. Martin co-founded the OLH in 2013 with Dr Caroline Edwards and went on to work widely in open access and HE policy. He has appeared before the UK House of Commons Select Committee BIS Inquiry into Open Access, writing for the British Academy Policy Series on the topic, been a steering-group member of the OAPEN-UK project, the Jisc National Monograph Strategy Group, the SCONUL Strategy Group on Academic Content and Communications, the Open Knowledge Foundation’s Open Access Steering Group, the Jisc Scholarly Communications Advisory Group, the Collaborative Knowledge Foundation advisory board, the California Digital Library/University of California Press’s Humanities Book Infrastructure advisory board, and the HEFCE Open Access Monographs Expert Reference Panel (2014), the Universities UK OA Monographs Working Group (2016-). Martin is a Plan S Ambassador and is currently running Work Package 3 of the COPIM project, funded by Research England and the Arcadia Foundation.

As a result of this policy work, Martin was named as one of the Guardian’s five finalists for higher education’s most inspiring leader 2017. In 2018, Martin was awarded the KU Leuven Medal of Honour in the Humanities and Social Sciences and alongside co-contributors and the editor won the Electronic Literature Organization’s N. Katherine Hayles Award for The Bloomsbury Handbook of Electronic Literature. In 2020, Martin was elected a Fellow of the English Association. In 2021, Martin was named by the Shaw Trust as one of the 100 most influential disabled people in the UK. Martin is also the developer of several digital humanities / computational projects. In 2018 he co-founded Janeway with Andy Byers, the OLH's in-house open source digital publishing platform.

Martin's academic career has been equally illustrious. He is the author of twelve academic monographs on topics ranging from contemporary American and British fiction, histories and philosophies of technology, evaluative cultures in the academy, and technological mutations in scholarly publishing. Martin has also co-edited two essay collections on scholarly communications. In 2019, Martin was awarded the prestigious Philip Leverhulme Prize for Literary Studies by the Leverhulme Trust. Martin is currently Principal R&D Developer at CrossRef, working on experimental research and development projects for Labs. He is also the Professor of Literature, Technology and Publishing at Birkbeck, University of London.

**Comment by joemull** [comment]
Closed by #230
