### ISSUE TITLE
Changes to Newsletter & annual reports page

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/hourglass#265]
# Newsletters
- [x]  no news letters linked for 2023
- [ ] news letters themselves have a very different page styling (background of page, not news letter) such that they don't seem to be part of the same site - at the very least the page background needs to be the same colour or have them open in a new tab.
- [ ] When on a newsletter, there is no way back to the main site until you scroll down to the bottom - the OLH logo is not a home link, but it is a home link on the main site - this will be confusing. - can the logo at the top be a link back to the news letter page.
- [ ] When landing on a news letter it is not clear which one it is - there is a date on the link to it, but no date on the newsletter page itself.
- [ ] The news letter headings are in title case - not sure whether that should be changed, as that's part of the actual news letter which is known to be older.

# Annual Reports
- [ ] 2022 - not all headings are sentence case (some are).
- [ ] 2022 - links through to a news item on an ORE report which also has headings that are not sentence case.
- [ ] 2021 - not all headings are sentence case - mostly missing the full stop at the end.
- [ ] 2020 - headings are in green instead of black
- [ ] 2020 - headings are not sentence case - missing the full stop
- [ ] 2019 - first line is missing a hyphen, "publishing in open access formats" this should be "open-access formats."

**Comment by PaulaClementeVega** [comment]
**Newsletters**

Name (Newsletter) should read in plural as Newsletters
Newsletter and report links should open in a new tab

**Comment by joemull** [comment]
Note to self: ["External Links, New Tabs, and Accessibility"](https://codersblock.com/blog/external-links-new-tabs-and-accessibility/)

**Comment by joemull** [comment]
Links for 2023 newsletters:

- [ ] Autumn https://mailchi.mp/openlibhums/newsletter-16925226
- [ ] Summer https://mailchi.mp/openlibhums/newsletter-16910118
- [ ] Winter https://mailchi.mp/openlibhums/newsletter-16897570

**Comment by joemull** [comment]
Thanks @StephDriver! I'd love your thoughts on https://github.com/BirkbeckCTP/hourglass/issues/306 when you have time
