### ISSUE TITLE
Changes to info for readers and authors

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/hourglass#266]
- [x] under Publish with us, Call for Papers should not be capitalised -> call for papers.
- [x] FAQs links correctly to the readers section of the FAQ page, but that is part way down the FAQ page and there is no heading visible when you land to show that's were you are.  the heading just says 'for readers & authors' ->update this to FAQ for readers & authors.
- [ ] get our newsletter link at bottom of the page links to a page that has very different styling and so doesn't look like its part of the same site. - and as external should be opening in a new tab.
- [x] twitter link should now be X
- [x] suggestion - the external links should open in a new tab/window, e.g. the links to social media at the bottom.
- [x] when on mobile/narrow window, there is a large empty space at the bottom of the page to scroll through before reaching the footer: 
<img width="492" alt="image" src="https://github.com/BirkbeckCTP/hourglass/assets/5330770/61082c16-6460-4a98-8474-ef24645d2484">

**Comment by PaulaClementeVega** [comment]
Remove Masdodon link and add Bluesky instead: [https://bsky.app/profile/openlibhums.bsky.social ](url)
