### ISSUE TITLE
Changes to Privacy page

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/hourglass#270]
- [x] headings other than the main page heading are in title case 
- [x] consider punctuation styles for bullet points - this is not the same as on the policies page #271 
- [x] Twitter should now be X (at end of page under  Registration and authentication.
- [x] Sentry and Uptime Robot - is it Data or data.  Other defined terms on this page are not capitalised in the descriptions.
- [x] link the contact us bit to the contact us page instead of putting an address here?
- [x] privacy policy is linked when registering, but I cannot find it otherwise within the navigation - this needs to be something people can find again and refer back to if they wish at any point, especially in regards to making a GDPR related query.

**Comment by ajrbyers** [comment]
>  privacy policy is linked when registering, but I cannot find it otherwise within the navigation - this needs to be something people can find again and refer back to if they wish at any point, especially in regards to making a GDPR related query.

Its available in the footer block which is, generally, where this kind of thing is.

<img width="964" alt="image" src="https://github.com/BirkbeckCTP/hourglass/assets/8321378/672a893b-3510-43fd-bc3b-ea59363f03af">

**Comment by StephDriver** [comment]
marked the privacy policy link task as complete in light of @ajrbyers comment.
