### ISSUE TITLE
OLH Journal Applications

### ISSUE THREAD

**Issue by the-blochian** [BirkbeckCTP/hourglass#278]
![OLH journal applications](https://github.com/BirkbeckCTP/hourglass/assets/146351903/ad51c099-9f27-46f7-887a-b3a2904a302c)
Please update "Expression of Interest Form" to "Journal Application Form". Here's the page URL: https://www.openlibhums.org/site/olh-journal-applications/

**Comment by S-Haime** [comment]
Done
