### ISSUE TITLE
Changes to Become a Supporter 

### ISSUE THREAD

**Issue by Astronaut-resting** [BirkbeckCTP/hourglass#281]
- [x] inconsistency between number of library supporters in text and in infographic: 300+ or 340+? Jarring when reading. Suggest update to 340+ if that is what we are saying more generally in the copy. 
- [x] link required for Library Brochure
- [x] Needs [platinum badge](https://birkbeckuol.sharepoint.com/sites/ac-ts-arts-olh/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fac-ts-arts-olh%2FShared%20Documents%2FGeneral%2FEditorial%2FExternal%20Communications%2FHigher%20Tier%20Supporter%20Badges%20(2023)%2FOLH%20Supporter%20Badges%202023.zip&parent=%2Fsites%2Fac-ts-arts-olh%2FShared%20Documents%2FGeneral%2FEditorial%2FExternal%20Communications%2FHigher%20Tier%20Supporter%20Badges%20(2023)) adding here?
- [x] Theo quote: should read [The] OLH puts a lot back into the academic community

**Comment by joemull** [comment]
- [ ] Update the higher supporter badge for 2024

![Supporter2024](https://github.com/BirkbeckCTP/hourglass/assets/47217308/01c5fe2f-0f7c-4217-92df-f9671ba73823)
