### ISSUE TITLE
Changes to FAQs

### ISSUE THREAD

**Issue by Astronaut-resting** [BirkbeckCTP/hourglass#283]
Libraries:

- [ ] You can use our calculator to assess your membership fee. Needs link to calculator 
- [x] What makes the OLH different from other academic publishers? has line breaks between paragraphs that are too big. 

Editors/Authors: 

- [x] Why should I publish Open Access? Has an extra line breaks with one of the paragraphs 

- [x] The OLH has received several awards for our innovations in digital publishing and many articles in our journals have received awards and prizes from their scholarly communities. needs link 

- [x] I am interested in the OLH project. How can I participate? extra spacing 

- [x] Open Library of Humanities journal link for how to participate needs to go to https://www.openlibhums.org/site/olh-journal/ link

**Comment by joemull** [comment]
- [ ] Under For Readers & Authors under "Why should I publish OA with the OLH" - CHANGE Open Access publishers often charge Author Processing Fees (APCs) to Article Processing Charges (APCs)
- [ ] Under For Editors "How would the OLH support my journal" - CHANGE "Stanford university, which are world leaders in..." 
- [ ] Also under For Editors - What Makes the OLH different - "This (model) of collective funding..." please DELETE parentheses here.
