### ISSUE TITLE
Changes to Reading List

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/hourglass#284]
[SIOBHAN WORKING ON THIS]

Proofing by CE: 

- [x] FORMATTING OF CLOSE SINGLE QUOTATION MARKS - needs to be rich text.
SH: What does this mean?

- [x] Adema, Janneke - LINK BROKEN.

- [x] Adema, Janneke, and Gary Hall - LINK BROKEN.

- [x] Adema, Janneke and Moore, Samuel,'Scaling" - ADD SPACE between Samuel and Scaling.

- [x] Ancion, Zoe et al... Open Access.' Science - REPLACE full stop with comma.

- [x] Beverungen, A., S. Bohm, and C. Land - LINK BROKEN.

- [x] Chan, Leslie - Ottawa Press, (2019) DELETE open bracket.

- [x] Eve, Martin - <https://www.martineve.com/2018/01/21/how-learned-societies-could-flip-to-oa-using-a-consortial-model/> LINK BROKEN.

- [x] Eve, Martin - <https://www.martineve.com/2017/02/13/how-much-does-it-cost-to-run-a-small-scholarly-publisher/> LINK BROKEN.

- [x] Eve, Martin - <https://www.martineve.com/2017/04/01/librarian-evaluation-of-non-apc-oa-models-in-the-age-of-open-access/> LINK BROKEN

- [x] Eve, Martin - <https://www.martineve.com/2017/03/11/on-the-economics-of-flipping-subscription-journals/> LINK BROKEN

- [x] Eve, Martin - <https://www.martineve.com/2018/01/19/open-access-resources-and-evaluation-or-why-oa-journals-might-fare-badly-in-terms-of-usage/> LINK BROKEN

- [x] Eve, Martin and Byers, Andy - 31: 15, 1–4 (2018) CHANGE TO 31: 15 (2018), 1–4

- [x] Eve, Martin, PCV and CE '. LIBER - REPLACE full stop with a COMMA.

- [x] Eve, Martin Paul, Kitty Inglis, David Prosser, Lara Speicher, and Graham Stone - ADD page numbers 89-102 after (2017)

- [x] Eve, Martin Paul, and Jonathan Gray (Eds.) Reassembling Scholarly Communications: Histories, Infrastructures, and Global Politics of Open Access. DELETE full stop and ITALICISE book title

- [x] François Waldner, F1000Res 5 (2016): 632: ITALICISE F1000Res, 5 (2016), (DELETE full colon).

- [x] Lawson, Stuart, Jonathan Gray, and Michele Mauri, - ADD ISSUE NUMBER in - 2(1)(2016)

- [x] ‘More Institutions Consider Ending Their “big Deals” with Publishers’, Inside Higher Ed, 2018 <https://www.insidehighered.com/news/2018/05/08/more-institutions-consider-ending-their-big-deals-publishers> [accessed 8 May 2018] LINK AND BIBLIOGRAPHIC DETAILS DON'T MATCH - UPDATE???

- [x] ‘Open Access Publishing and the Future of the University’, Institute for Social Futures <http://www.lancaster.ac.uk/social-futures/2016/09/open-access-publishing-and-the-future-of-the-university/> LINK ROT.

- [x] Reinsfelder, Thomas L., and Caitlin A. Pike - BOLD Pike, Caitlin A. (and make SURNAME first)

- [x] Solomon, David J., Mikael Laakso, and Bo-Christer Björk, ‘Converting Scholarly Journals to Open Access: A Review of Approaches and Experiences’, 2016 <https://dash.harvard.edu/handle/1/27803834> [accessed 26 January 2018] - LINK ROT

- [x] Suri, Natasha, ‘Academic Librarian Engagement with Open Access in the UK: Support, Advocacy and Education’, unpublished Master’s dissertation, City, University of London - ADD DATE at the end (2018)

- [x] Wentzel, Annica, ‘Sweden stands up for open access – cancels agreement with Elsevier’, OpenAccess.se, 2018 <http://openaccess.blogg.kb.se/2018/05/16/sweden-stands-up-for-open-access-cancels-agreement-with-elsevier/> WRONG LINK

REPLACE WITH: https://www.kb.se/samverkan-och-utveckling/nytt-fran-kb/nyheter-samverkan-och-utveckling/2018-05-16-sweden-stands-up-for-open-access---cancels-agreement-with-elsevier.html

- [x] If you would like to contribute suggestions to this list, please contact our Marketing Officer Paula Clemente Vega. WRONG LINK - link to Contact Us pre-set form.

**Comment by S-Haime** [comment]
I'll need to check what style (derivative) this is meant to be. I am seeing signs of MLA, Harvard and something I can't place. As a publisher, I think we need to be more consistent on this. (Sorry - ex-reading lists library assistant!) Once I know what it is intended to be, I can fix it. Alternatively, I can try and just make it consistent and leave it there for the moment.

**Comment by S-Haime** [comment]
Unified names - MLA style. Will need general review from @the-blochian and @Astronaut-resting as to what style this list ought to be.

(I am suggesting MLA as there are a lot of pre-existing MLA elements and would cause least edits. As we are humanities press, it also wouldn't be out of place. Apologies for nitpicking! Reading lists used to be my entire job ;) )

**Comment by the-blochian** [comment]
I'm happy to go with whatever causes the least amount of work at this stage! I usually write in Chicago (or something derived from it), but there were 2 of us writing pages that included works cited and we hadn't checked beforehand. Sorry!

**Comment by S-Haime** [comment]
Brilliant - @joemull just let me know when you have merged and I can do a copyedit 2 :)

(If you'd like any more issues addressing this morning, let me know as I don't know when you'll be merging the branch).

**Comment by joemull** [comment]
OK, I think the changes you've already made to this list should be enough to publicise the site next week, but I will have a closer look today.

Perhaps after that we can return to standardising these according to a style like Chicago (yay Chicago). We'll need to do it consistently with other pages where there are references at the bottom, like the OA movement page, and we also haven't set on a visual design for these lists that we're happy with, so it can go on the list of changes to make post-launch.

**Comment by joemull** [comment]
Added a [separate issue for these things](https://github.com/BirkbeckCTP/hourglass/issues/297).
