### ISSUE TITLE
Mission v. Vision statements

### ISSUE THREAD

**Issue by the-blochian** [BirkbeckCTP/hourglass#305]
- [x] We need to reinstate the old / original mission statement and make it clear that the new statement is a vision statement.

Can you add Our Mission statement to the OLH homepage?

Mission statement / Our mission is:

Our mission is to support and extend open access to scholarship in the humanities – for free, for everyone, for ever.  
 
Vision statement / Our vision is:

We support and extend open access to scholarship in the humanities by bringing journals back into community ownership and developing our own not-for-profit publishing software. 

<img width="1202" alt="Screenshot 2024-02-16 at 16 24 25" src="https://github.com/BirkbeckCTP/hourglass/assets/146351903/a5c61271-a486-4402-a847-8ae548a356ca">

**Comment by joemull** [comment]
@the-blochian would you like the mission statement to go at the top, in the blue box, replacing the current copy?

![Image](https://github.com/BirkbeckCTP/hourglass/assets/47217308/9c92f2cd-c58d-4ae5-ae5f-17144a622b8b)

Or perhaps somehow in combination with the vision, lower down? (With better styling than this)

![Image](https://github.com/BirkbeckCTP/hourglass/assets/47217308/06dc6f53-aab0-4108-b87c-64caf9a8c71f)

Can just talk about this in the design meeting if you prefer
