### ISSUE TITLE
WCAG: Readable

### ISSUE THREAD

**Issue by StephDriver** [BirkbeckCTP/hourglass#340]
# Summary

This review considered:
1. Language of Page
2. Language of Parts

- https://github.com/BirkbeckCTP/janeway/issues/4139

# Audit Results

## Language of Page
Technique H57
`lang="en-GB"` used inside `<html>` tag at top of each page.

# Language of Parts
The main place where languages other then en-GB are present is the Journals page as not all are journals written in English. Where a non-English name has been given, it is not marked up for language.  For example:

![Image](https://github.com/BirkbeckCTP/hourglass/assets/5330770/0c3f4de2-112d-42dd-8d9d-9bfa179f4cdf)

```html
<p><i>Digital Studies / Le champ numérique&nbsp;</i>is a leading refereed academic journal in the Digital Humanities. It is published for the Alliance of Digital Humanities Organisations under the direction of the Canadian Society for Digital Humanities/Société canadienne des humanités numériques (CSDH/SCHN).</p>
```
see [Technique H58](https://www.w3.org/WAI/WCAG22/Techniques/html/H58.html) for information on `lang` attribute.

**Comment by joemull** [comment]
I've now added issues to address this category.

**Comment by StephDriver** [comment]
SD: JM add this "set language of parts" functionality to user content list for future phases of a11y project, then can close.
