### ISSUE TITLE
Integrate with consortial billing plugin

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/hourglass#6]
We will need to find a way to make the consortial billing plugin work in this subtheme with a consistent look and feel between pages. This may involve updates to the [consortial billing plugin](https://github.com/BirkbeckCTP/consortial_billing) to bring it inline with the plugin architecture that has become standardized more recently.

**Comment by ajrbyers** [comment]
This sounds like a lot of work. We should consider dumping the CB plugin and building a newer one that incorporates the two things it gets used for:

1. Signups
2. Display of approved signups
